baseURL = "http://localhost:1313"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Yuxian Xu"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright Â© Yuxian Xu 2022"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/mwkybyej"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Surrey, B.C, Canada."
email = "yuxian.xu@gmail.com"
openingHours = "Open from 7:30am to 4:30pm (close at 5pm Sundays)"
phone = "+(1) 778 *** 3137"


[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons

[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/yuxianxu"
weight = 1
[[params.social]]
icon = "fa-github-square"
url = "https://www.github.com/yuxianxu"
weight = 2
